/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.41
 * Generated at: 2021-03-28 18:29:47 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.board;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class detail_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(5);
    _jspx_dependants.put("/WEB-INF/views/board/../../views/include/includeFile.jsp", Long.valueOf(1616956166000L));
    _jspx_dependants.put("jar:file:/D:/project_hotel/hotel/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/hotel_booking/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/views/board/../include/includeFile.jsp", Long.valueOf(1616956166000L));
    _jspx_dependants.put("/WEB-INF/views/board/../menu.jsp", Long.valueOf(1616662024000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1616952930000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.release();
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("\r\n");
      if (_jspx_meth_c_005fset_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("<!-- 제이쿼리 -->\r\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/jquery-3.5.1.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<!-- css -->\r\n");
      out.write("<!-- 챗봇 -->\r\n");
      out.write("<link href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.css\" type=\"text/css\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/chatstyle.css\" rel=\"stylesheet\">  \r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/vesources/css/style.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/bootstrap.css\">\r\n");
      out.write("\r\n");
      out.write("<!-- 자바스크립트 -->\r\n");
      out.write("<!-- <script src=\"https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js\"></script> -->\r\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/bootstrap.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<!-- 사용자 자바스크립트 -->\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("/* \tif ('");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${msg}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("'!=''){\r\n");
      out.write("\t\talert('");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${msg}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("');\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tif ('");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${param.msg}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("'!=''){\r\n");
      out.write("\t\talert('");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${param.msg}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("');\r\n");
      out.write("\t} */\r\n");
      out.write("\t\r\n");
      out.write("</script> ");
      out.write("    \r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>문의사항 상세조회</title>\r\n");
      out.write("<!-- 핸들바 탬플릿 cdn추가 -->\r\n");
      out.write("<script src=\"https://cdnjs.cloudflare.com/ajax/libs/handlebars.js/4.7.7/handlebars.min.js\"></script>\r\n");
      out.write(" <!-- 탬플릿 소스 :게시판 리스트-->\r\n");
      out.write(" <script id=\"template_source\" type=\"text/x-handlebars-template\">\r\n");
      out.write("    {{#each .}}\r\n");
      out.write("\t\t{{level relevel}}\r\n");
      out.write("\t\t<div>\r\n");
      out.write("\t\t\t<input type=\"hidden\" class=\"restep\" value=\"{{restep}}\">\r\n");
      out.write("\t\t\t<input type=\"hidden\" class=\"relevel\" value=\"{{relevel}}\">\r\n");
      out.write("\t\t\t<input type=\"hidden\" class=\"rnum\" value=\"{{rnum}}\">\r\n");
      out.write("\t\t\t<input type=\"text\" class=\"userID\" value=\"{{userID}}\">\r\n");
      out.write("\t\t\t<br>\r\n");
      out.write("\t\t\t<textarea rows=\"3\" cols=\"20\" class=\"content\">{{content}}</textarea><br>\r\n");
      out.write("\t\t\t<button class=\"btnReplyUpdate\">수정</button>\r\n");
      out.write("\t\t\t<button class=\"btnReplyDelete\">삭제</button>\r\n");
      out.write("\t\t\t<button class=\"btnReply\">댓글</button>\r\n");
      out.write("\t\t\t<div class='replyAdd'></div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("    {{/each}}\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<!-- 탬플릿 소스 : 댓글 추가 -->\r\n");
      out.write(" <script id=\"template_source_reply\" type=\"text/x-handlebars-template\">\r\n");
      out.write("\t<div>\r\n");
      out.write("\t\t<input type=\"hidden\" id=\"restep\" value=\"{{restep}}\">\r\n");
      out.write("\t\t<input type=\"hidden\" id=\"relevel\" value=\"{{relevel}}\"><br>\r\n");
      out.write("\t\t<textarea rows=\"5\" cols=\"20\" id=\"replycontent\"></textarea><br>\r\n");
      out.write("\t\t<button class=\"btnReplyAdd\">추가</button>\r\n");
      out.write("\t</div>\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\r\n");
      out.write("\t\t$(function() {\r\n");
      out.write("\t\t\t//도움 버튼\r\n");
      out.write("\t\t\t$('#btnGood').click(function() {\r\n");
      out.write("\t\t\t\tconst bnum = $('#bnum').val();\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\t\ttype:'get',\r\n");
      out.write("\t\t\t\t\turl:'");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/board/goodcnt/'+bnum,\r\n");
      out.write("\t\t\t\t\tdataType:'json',\r\n");
      out.write("\t\t\t\t\tsuccess: function(result) {\r\n");
      out.write("\t\t\t\t\t\t$('#goodcnt').html(result.goodcnt);\r\n");
      out.write("\t\t\t\t\t\t$('#nongoodcnt').html(result.nongoodcnt);\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\terror: function(result) {\r\n");
      out.write("\t\t\t\t\t\talert('error');\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\t//비도움 버튼\r\n");
      out.write("\t\t\t$('#btnNonGood').click(function() {\r\n");
      out.write("\t\t\t\tconst bnum = $('#bnum').val();\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\t\ttype:'get',\r\n");
      out.write("\t\t\t\t\turl:'");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/board/nongoodcnt/'+bnum,\r\n");
      out.write("\t\t\t\t\tdataType:'json',\r\n");
      out.write("\t\t\t\t\tsuccess: function(result) {\r\n");
      out.write("\t\t\t\t\t\t//alert(result);\r\n");
      out.write("\t\t\t\t\t\t$('#goodcnt').html(result.goodcnt);\r\n");
      out.write("\t\t\t\t\t\t$('#nongoodcnt').html(result.nongoodcnt);\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\terror: function(result) {\r\n");
      out.write("\t\t\t\t\t\talert('error');\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t//수정버튼을 눌렀을때\r\n");
      out.write("\t\t\t$('#btnModify').click(function() {\r\n");
      out.write("\t\t\t\tconst bnum = $('#bnum').val();\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t\t//userID 체크\r\n");
      out.write("\t\t\t\tconst session_userID = '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.userID}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("';\r\n");
      out.write("\t\t\t\tconst userID = $('#userID').val();\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t\tif (userID != session_userID){\r\n");
      out.write("\t\t\t\t\talert('수정권한이 없습니다');\r\n");
      out.write("\t\t\t\t\treturn ;\t\t\t\t\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tlocation.href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/board/modify/\"+bnum;\t\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t//목록버튼을 눌렀을때\r\n");
      out.write("\t\t\t$('#btnList').click(function(e) {\r\n");
      out.write("\t\t\t\te.preventDefault();\r\n");
      out.write("\t\t\t\tlocation.href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/board/\";\t\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t/* -------------------댓글처리------------------------- */\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t//댓글추가 버튼을 눌렀을때\r\n");
      out.write("\t\t\t$('body').on('click', '.btnReplyAdd', function() {\r\n");
      out.write("\t\t\t\t//userID체크\r\n");
      out.write("\t\t\t\tconst session_userID = '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.userID}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("';\r\n");
      out.write("\t\t\t\tif (session_userID==''){\r\n");
      out.write("\t\t\t\t\talert('로그인 후 이용해 주세요');\r\n");
      out.write("\t\t\t\t\treturn ;\t\t\t\t\r\n");
      out.write("\t\t\t\t}\t\t\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tconst bnum = $('#bnum').val();\r\n");
      out.write("\t\t\t\tconst replycontent = $(this).parent().find('#replycontent').val(); \r\n");
      out.write("\t\t\t\tconst restep = $(this).parent().find('#restep').val();\r\n");
      out.write("\t\t\t\tconst relevel = $(this).parent().find('#relevel').val();\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tif (replycontent==''){\r\n");
      out.write("\t\t\t\t\talert('댓글 내용을 입력해주세요');\r\n");
      out.write("\t\t\t\t\t$('#replycontent').focus();\r\n");
      out.write("\t\t\t\t\treturn;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\t\ttype:'post',\r\n");
      out.write("\t\t\t\t\tcontentType: \"application/json\",\r\n");
      out.write("\t\t\t\t\turl: '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/reply/',\r\n");
      out.write("\t\t\t\t\tdata : JSON.stringify({bnum:bnum,content:replycontent,restep:restep,relevel:relevel}),//json문자열\r\n");
      out.write("\t\t\t\t\tdataType: 'text',\r\n");
      out.write("\t\t\t\t\tsuccess: function(result) {\r\n");
      out.write("\t\t\t\t\t\t//alert(result);\r\n");
      out.write("\t\t\t\t\t\t//원본 댓글추가 html삭제\r\n");
      out.write("\t\t\t\t\t\t$('#replyAdd').html('');\r\n");
      out.write("\t\t\t\t\t\t//댓글의 댓글 추가 삭제\r\n");
      out.write("\t\t\t\t\t\tconsole.log($(this).parent().parent().html());\r\n");
      out.write("\t\t\t\t\t\treplyList() ; //댓글 리스트 \r\n");
      out.write("\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\terror: function(result) {\r\n");
      out.write("\t\t\t\t\t\talert('error');\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t//원본의 댓글 버튼을 눌렀을때\r\n");
      out.write("\t\t\t$('#btnReply').on('click',function() {\r\n");
      out.write("\t\t\t\t//alert(restep);\r\n");
      out.write("\t\t\t\t//alert(relevel);\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\tconst data = {'restep':0, 'relevel':0}; \r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t//탬플릿을 이용하여 화면에 출력\r\n");
      out.write("\t\t\t\tvar source = $('#template_source_reply').html();\r\n");
      out.write("\t\t        var template = Handlebars.compile(source);\r\n");
      out.write("\t\t        $('#replyAdd').html(template(data));\t\t\t\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t//댓글의 댓글 버튼을 눌렀을때\r\n");
      out.write("\t\t\t$('#replyList').on('click', '.btnReply', function() {\r\n");
      out.write("\t\t\t\tconst restep = $(this).parent().find('.restep').val();\r\n");
      out.write("\t\t\t\tconst relevel = $(this).parent().find('.relevel').val();\r\n");
      out.write("\t\t\t\tconst data = {restep:restep, relevel:relevel};\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t//탬플릿을 이용하여 화면에 출력\r\n");
      out.write("\t\t\t\tvar source = $('#template_source_reply').html();\r\n");
      out.write("\t\t        var template = Handlebars.compile(source);\r\n");
      out.write("\t\t        $(this).parent().find('.replyAdd').html(template(data));\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t      //댓글의 수정 버튼을 눌렀을때\r\n");
      out.write("\t\t\t\t$('#replyList').on('click', '.btnReplyUpdate', function() {\r\n");
      out.write("\t\t\t\t\tconst rnum = $(this).parent().find('.rnum').val();\r\n");
      out.write("\t\t\t\t\tconst userID = $(this).parent().find('.userID').val();\r\n");
      out.write("\t\t\t\t\tconst content = $(this).parent().find('.content').val();\r\n");
      out.write("\t\t\t\t\tconsole.log(rnum);\r\n");
      out.write("\t\t\t\t\tconsole.log(userID);\r\n");
      out.write("\t\t\t\t\tconsole.log(content);\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t//userID체크\r\n");
      out.write("\t\t\t\t\tconst session_userID = '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.userID}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("';\r\n");
      out.write("\t\t\t\t\tif (userID != session_userID){\r\n");
      out.write("\t\t\t\t\t\talert('수정권한이 없습니다');\r\n");
      out.write("\t\t\t\t\t\treturn ;\t\t\t\t\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\t\t\ttype:'put', //수정\r\n");
      out.write("\t\t\t\t\t\tcontentType: \"application/json\",\r\n");
      out.write("\t\t\t\t\t\turl: '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/reply/',\r\n");
      out.write("\t\t\t\t\t\tdata : JSON.stringify({rnum:rnum,userID:userID,content:content}),//json문자열\r\n");
      out.write("\t\t\t\t\t\tdataType: 'text',\r\n");
      out.write("\t\t\t\t\t\tsuccess: function(result) {\r\n");
      out.write("\t\t\t\t\t\t\talert(result);\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\t\terror: function(result) {\r\n");
      out.write("\t\t\t\t\t\t\talert('error');\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\t//댓글의 삭제 버튼을 눌렀을때\r\n");
      out.write("\t\t\t\t$('#replyList').on('click', '.btnReplyDelete', function() {\r\n");
      out.write("\t\t\t\t\tconst rnum = $(this).parent().find('.rnum').val();\r\n");
      out.write("\t\t\t\t\tconst userID = $(this).parent().find('.userID').val();\r\n");
      out.write("\t\t\t\t\tconsole.log(rnum);\r\n");
      out.write("\t\t\t\t\tconsole.log(userID);\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t//userID 체크\r\n");
      out.write("\t\t\t\t\tconst session_userID = '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.userID}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("';\r\n");
      out.write("\t\t\t\t\tif (userID != session_userID) {\r\n");
      out.write("\t\t\t\t\t\talert('삭제권한이 없습니다');\r\n");
      out.write("\t\t\t\t\t\treturn ;\t\t\t\t\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\t\t\ttype:'delete', //삭제\r\n");
      out.write("\t\t\t\t\t\turl: '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/reply/'+rnum,\r\n");
      out.write("\t\t\t\t\t\tdataType: 'text',\r\n");
      out.write("\t\t\t\t\t\tsuccess: function(result) {\r\n");
      out.write("\t\t\t\t\t\t\talert(result);\r\n");
      out.write("\t\t\t\t\t\t\treplyList() ; //댓글 리스트 \r\n");
      out.write("\t\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\t\terror: function(result) {\r\n");
      out.write("\t\t\t\t\t\t\talert('error');\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\t//댓글 리스트 조회\r\n");
      out.write("\t\t\t\tfunction replyList() {\r\n");
      out.write("\t\t\t\t\tconst bnum = $('#bnum').val();\r\n");
      out.write("\t\t\t\t\t//alert(bnum);\r\n");
      out.write("\t\t\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\t\t\ttype:'get',\r\n");
      out.write("\t\t\t\t\t\turl: '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/reply/'+bnum,\r\n");
      out.write("\t\t\t\t\t\tdataType: 'json',\r\n");
      out.write("\t\t\t\t\t\tsuccess: function(result) {\r\n");
      out.write("\t\t\t\t\t\t\t//alert(result);\r\n");
      out.write("\t\t\t\t\t\t\tconsole.log(result);\r\n");
      out.write("\t\t\t\t\t\t\t//핸들바 헬퍼 작성\r\n");
      out.write("\t\t\t\t\t\t\tHandlebars.registerHelper('level', function(relevel) {\r\n");
      out.write("\t\t\t\t\t\t\t\tvar result = '';\r\n");
      out.write("\t\t\t\t\t\t\t\tfor(i=0; i<relevel; i++){\r\n");
      out.write("\t\t\t\t\t\t\t\t\tresult += '@';\r\n");
      out.write("\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t\treturn result;\r\n");
      out.write("\t\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t//탬플릿을 이용하여 화면에 출력\r\n");
      out.write("\t\t\t\t\t\t\tvar source = $('#template_source').html();\r\n");
      out.write("\t\t\t\t            var template = Handlebars.compile(source);\r\n");
      out.write("\t\t\t\t            $('#replyList').html(template(result));\t\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\t\terror: function(result) {\r\n");
      out.write("\t\t\t\t\t\t\talert('error');\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t});\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t}\t\t\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\treplyList();\r\n");
      out.write("\t});\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("\r\n");
      if (_jspx_meth_c_005fset_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("<!-- 제이쿼리 -->\r\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/jquery-3.5.1.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<!-- css -->\r\n");
      out.write("<!-- 챗봇 -->\r\n");
      out.write("<link href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.css\" type=\"text/css\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/chatstyle.css\" rel=\"stylesheet\">  \r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/vesources/css/style.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/bootstrap.css\">\r\n");
      out.write("\r\n");
      out.write("<!-- 자바스크립트 -->\r\n");
      out.write("<!-- <script src=\"https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js\"></script> -->\r\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/bootstrap.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<!-- 사용자 자바스크립트 -->\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("/* \tif ('");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${msg}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("'!=''){\r\n");
      out.write("\t\talert('");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${msg}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("');\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tif ('");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${param.msg}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("'!=''){\r\n");
      out.write("\t\talert('");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${param.msg}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("');\r\n");
      out.write("\t} */\r\n");
      out.write("\t\r\n");
      out.write("</script> ");
      out.write("   \r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<script type=\"text/javascript\">\n");
      out.write("\t$(function() {\r\n");
      out.write("\t\t//로그인,로그아웃,회원가입 show 여부\r\n");
      out.write("\t\tif ('");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.userID}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("' == ''){\r\n");
      out.write("\t\t\t$('#aLogin').show();\t\r\n");
      out.write("\t\t\t$('#aJoin').show();\t\r\n");
      out.write("\t\t\t$('#aLogout').hide();\r\n");
      out.write("\t\t\t$('#aBookingList').hide();\r\n");
      out.write("\t\t}else{\r\n");
      out.write("\t\t\t$('#aLogin').hide();\t\r\n");
      out.write("\t\t\t$('#aJoin').hide();\t\r\n");
      out.write("\t\t\t$('#aLogout').show();\r\n");
      out.write("\t\t\t$('#aBookingList').show();\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t//메인\r\n");
      out.write("\t\t$('#aHome').on('click', function(e) {\r\n");
      out.write("\t\t\t$(this).attr('href', '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/main');\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t//호텔위치\r\n");
      out.write("\t\t$('#aHotel').on('click', function(e) {\r\n");
      out.write("\t\t\t$(this).attr('href', '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/info/');\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t//문의사항\r\n");
      out.write("\t\t$('#aBoardList').on('click', function(e) {\r\n");
      out.write("\t\t\t$(this).attr('href', '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/board/')\r\n");
      out.write("\t\t})\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t//예약하기\r\n");
      out.write("\t\t$('#aBooking').on('click', function(e) {\r\n");
      out.write("\t\t\t$(this).attr('href', '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/booking/book_1')\r\n");
      out.write("\t\t})\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t//챗봇\r\n");
      out.write("\t\t$('#aChat').on('click', function(e) {\r\n");
      out.write("\t\t\te.preventDefault();\r\n");
      out.write("\t\t\t$(location).attr('href', '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/chatbot');\r\n");
      out.write("\t\t})\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t//로그아웃\r\n");
      out.write("\t\t$('#aLogout').on('click', function(e) {\r\n");
      out.write("\t\t\te.preventDefault();\r\n");
      out.write("\t\t\tvar result = confirm ('로그아웃 하시겠습니까?');\r\n");
      out.write("\t\t\tif (result){\r\n");
      out.write("\t\t\t\t$(location).attr('href', '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/logout');\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t//로그인\r\n");
      out.write("\t\t$('#btnLogin').on('click', function(e) {\r\n");
      out.write("\t\t\t//아이디/패스워드 체크\r\n");
      out.write("\t\t\te.preventDefault(); //객체의 기본기능을 소멸\r\n");
      out.write("\t\t\t$('#loginForm').attr('action','");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/login');\r\n");
      out.write("\t\t\t$('#loginForm').attr('method','post');\r\n");
      out.write("\t\t\t$('#loginForm').submit();\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t//로그인 취소\r\n");
      out.write("\t\t$('#btnLoginCancel').on('click', function(e) {\r\n");
      out.write("\t\t\te.preventDefault();\r\n");
      out.write("\t\t\t$('#loginModal').modal('hide');\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\r\n");
      out.write("\t});\r\n");
      out.write("\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- Navbar -->\r\n");
      out.write("<nav class=\"navbar navbar-default\">\r\n");
      out.write("  <div class=\"container\">\r\n");
      out.write("    <div class=\"navbar-header\">\r\n");
      out.write("      <button type=\"button\" class=\"navbar-toggle\" data-toggle=\"collapse\" data-target=\"#myNavbar\">\r\n");
      out.write("        <span class=\"icon-bar\"></span>\r\n");
      out.write("        <span class=\"icon-bar\"></span>\r\n");
      out.write("        <span class=\"icon-bar\"></span>\t\t\r\n");
      out.write("\t\t</button>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<a class = \"navbar-brand\" href=\"\" id=\"aHome\">메인</a>\r\n");
      out.write("\t\t<a class = \"navbar-brand\" href=\"\" id=\"aHotel\">호텔위치</a>\r\n");
      out.write("\t\t<a class = \"navbar-brand\" href=\"\" id=\"aBoardList\">문의사항</a>\r\n");
      out.write("\t\t<a class = \"navbar-brand\" href=\"\" id=\"aBooking\">예약하기</a>\r\n");
      out.write("\t\t<a class = \"navbar-brand\" href=\"\" id=\"aChat\" >챗봇</a>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\r\n");
      out.write("    <div class=\"collapse navbar-collapse\" id=\"myNavbar\">\r\n");
      out.write("      <ul class=\"nav navbar-nav navbar-right\">\r\n");
      out.write("\t\t\t<li><a href=\"#\" data-toggle=\"modal\" data-target=\"#loginModal\" id=\"aLogin\">로그인</a></li>\r\n");
      out.write("\t\t\t<li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/member/add\" target=\"myframe\" id=\"aJoin\">회원가입</a></li>\r\n");
      out.write("\t\t\t<li><a href=\"#\" id=\"aMyinfo\" target=\"myframe\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.userID}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</a></li>\r\n");
      out.write("\t\t\t<li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/booking/Bookinglist\" target=\"myframe\" id=\"aBookingList\">예약조회</a></li>\r\n");
      out.write("\t\t\t<li><a href=\"\" id=\"aLogout\">로그아웃</a></li>\r\n");
      out.write("\t\t</ul>\r\n");
      out.write("\t</div>\t\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("  <!-- 로그인 Modal -->\r\n");
      out.write("  <div class=\"modal fade\" id=\"loginModal\" role=\"dialog\">\r\n");
      out.write("    <div class=\"modal-dialog modal-sm\">\r\n");
      out.write("      <div class=\"modal-content\">\r\n");
      out.write("\t\t<div class=\"modal-header\">\r\n");
      out.write("\t \t\t<h4 class=\"modal-title\">로그인</h4>\r\n");
      out.write("\t    </div>\r\n");
      out.write("        <div class=\"modal-body\">\t    \r\n");
      out.write("\t\t\t<form id =\"loginForm\">\r\n");
      out.write("\t\t\t  \t<div class=\"input-group\">\r\n");
      out.write("\t\t\t    \t<span class=\"input-group-addon\"><i class=\"glyphicon glyphicon-user\"></i></span>\r\n");
      out.write("\t\t\t    \t<input id=\"id\" type=\"text\" class=\"form-control\" name=\"userID\" placeholder=\"id\">\r\n");
      out.write("\t\t\t  \t</div>\r\n");
      out.write("\t\t\t  \t<div class=\"input-group\">\r\n");
      out.write("\t\t\t    \t<span class=\"input-group-addon\"><i class=\"glyphicon glyphicon-lock\"></i></span>\r\n");
      out.write("\t\t\t    \t<input id=\"password\" type=\"password\" class=\"form-control\" name=\"userPW\" placeholder=\"Password\">\r\n");
      out.write("\t\t\t  \t</div>\r\n");
      out.write("\t\t\t</form>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t</div>\r\n");
      out.write(" \t\t<div class=\"modal-footer\">\r\n");
      out.write(" \t\t\t<a href=\"\"  class=\"btn btn-primary\" id=\"btnLogin\">로그인</a>\r\n");
      out.write(" \t\t\t<a href=\"\" class=\"btn btn-success\" id=\"btnLoginCancel\">취소</a>\r\n");
      out.write("\t\t</div>      \r\n");
      out.write(" \t\t<div class=\"modal-footer\">\r\n");
      out.write(" \t\t\t<a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${apiURL}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("0\" id=\"aNaverLogin\"><img height=\"50\" src=\"http://static.nid.naver.com/oauth/small_g_in.PNG\" alt=\"네이버\"/></a>\r\n");
      out.write("\t\t</div>\t\t\t\r\n");
      out.write("\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</nav>");
      out.write("\r\n");
      out.write("<div class=\"container\">\r\n");
      out.write("\t");
      out.write("\r\n");
      out.write("\t<h2>상세조회</h2>\r\n");
      out.write("\t번호 : <input type=\"text\" id=\"bnum\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${resultMap.bdto.bnum}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" readonly=\"readonly\"> <br>\r\n");
      out.write("\t아이디 : <input type=\"text\" id=\"userID\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${resultMap.bdto.userID}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" readonly=\"readonly\"> <br>\r\n");
      out.write("\t제목 : ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${resultMap.bdto.subject}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(" <br>\r\n");
      out.write("\t내용 : <textarea rows=\"5\" cols=\"20\" readonly>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${resultMap.bdto.content}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</textarea><br>\r\n");
      out.write("\t<hr>\r\n");
      out.write("\t파일 : <br>\r\n");
      out.write("\t");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t<hr>\t\r\n");
      out.write("\t조회수 :  ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${resultMap.bdto.readcount}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(" \r\n");
      out.write("\t<button id=\"btnGood\">도움</button><span id=\"goodcnt\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${resultMap.bdto.goodcnt}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</span>\r\n");
      out.write("\t<button id=\"btnNonGood\">비도움</button><span id=\"nongoodcnt\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${resultMap.bdto.nongoodcnt}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</span>\r\n");
      out.write("\t<hr>\t\r\n");
      out.write("\t등록일자 :  ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${resultMap.bdto.regdate}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(" <br>\r\n");
      out.write("\t수정일자 :  ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${resultMap.bdto.modifydate}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(" <br>\r\n");
      out.write("\t<hr>\t\r\n");
      out.write("\t<button id=\"btnModify\">수정</button>\r\n");
      out.write("\t<button id=\"btnReply\">댓글</button>\r\n");
      out.write("\t<button id=\"btnList\">목록</button>\r\n");
      out.write("\t\r\n");
      out.write("\t<!-- 댓글 추가 -->\r\n");
      out.write("\t<div id=\"replyAdd\"></div>\r\n");
      out.write("\t\r\n");
      out.write("\t<!-- 댓글의 리스트 -->\r\n");
      out.write("\t<div id=\"replyList\">\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fset_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f0 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f0_reused = false;
    try {
      _jspx_th_c_005fset_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f0.setParent(null);
      // /WEB-INF/views/board/../include/includeFile.jsp(4,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setVar("path");
      // /WEB-INF/views/board/../include/includeFile.jsp(4,0) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setValue(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/board/../include/includeFile.jsp(4,0) '${pageContext.request.contextPath}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${pageContext.request.contextPath}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int _jspx_eval_c_005fset_005f0 = _jspx_th_c_005fset_005f0.doStartTag();
      if (_jspx_th_c_005fset_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f0);
      _jspx_th_c_005fset_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fset_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f1 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f1_reused = false;
    try {
      _jspx_th_c_005fset_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f1.setParent(null);
      // /WEB-INF/views/board/../../views/include/includeFile.jsp(4,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f1.setVar("path");
      // /WEB-INF/views/board/../../views/include/includeFile.jsp(4,0) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f1.setValue(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/board/../../views/include/includeFile.jsp(4,0) '${pageContext.request.contextPath}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${pageContext.request.contextPath}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int _jspx_eval_c_005fset_005f1 = _jspx_th_c_005fset_005f1.doStartTag();
      if (_jspx_th_c_005fset_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f1);
      _jspx_th_c_005fset_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f0_reused = false;
    try {
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent(null);
      // /WEB-INF/views/board/detail.jsp(297,1) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("file");
      // /WEB-INF/views/board/detail.jsp(297,1) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/board/detail.jsp(297,1) '${resultMap.bflist}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${resultMap.bflist}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("\t\t");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${file.filename}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write(" <br>\r\n");
            out.write("\t");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
      _jspx_th_c_005fforEach_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
    }
    return false;
  }
}
